FROM php:7.3-apache

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends wget git ${PHPIZE_DEPS} libzip-dev \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN set -ex \
    && docker-php-ext-install zip pdo_mysql \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN set -ex \
    && echo "\
xdebug.var_display_max_children = -1 \n\
xdebug.var_display_max_data = -1 \n\
xdebug.var_display_max_depth = -1 \n\
" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN set -ex \
    && a2enmod rewrite

COPY install_composer.sh /tmp/

RUN set -ex \
    && sh /tmp/install_composer.sh \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer \
    && composer global require hirak/prestissimo

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends libjpeg-dev libpng-dev libgif-dev \
    && docker-php-ext-install gd \
    && apt-get clean \
    && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN set -ex \
    && echo "\
alias cp='cp -i'\n\
alias egrep='egrep --color=auto'\n\
alias fgrep='fgrep --color=auto'\n\
alias grep='grep --color=auto'\n\
alias l.='ls -d .* --color=auto'\n\
alias ls='ls --color=auto'\n\
alias ll='ls -l --color=auto'\n\
alias l='ll'\n\
alias la='ls -la --color=auto'\n\
alias lh='ls -lha --color=auto'\n\
alias mv='mv -i'\n\
alias rm='rm -i'\n\
" >> /root/.bashrc

RUN set -ex \
    && cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

RUN set -ex \
    && usermod -u 1000 www-data
